export const USER_CREATED = 'USER_CREATED';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_DELETED = 'USER_DELETED';

export const SCHOOL_CREATED = 'SCHOOL_CREATED';
export const SCHOOL_UPDATED = 'SCHOOL_UPDATED';
export const SCHOOL_DELETED = 'SCHOOL_DELETED';

export const CLASS_CREATED = 'CLASS_CREATED';
export const CLASS_UPDATED = 'CLASS_UPDATED';
export const CLASS_DELETED = 'CLASS_DELETED';
