export const ROLE_ADMIN = 'ADMIN';
export const ROLE_SCHOOL_ADMIN = 'SCHOOL_ADMIN';
export const ROLE_TEACHER = 'TEACHER';
export const ROLE_STUDENT = 'STUDENT';

export const USER_ROLES = [
  ROLE_ADMIN,
	ROLE_SCHOOL_ADMIN,
	ROLE_TEACHER,
	ROLE_STUDENT
];
